Модалка (пустая)
NikitaVegas95/school_48 pull request #6
Opened 2023-07-02 19:58 UTC by NikitaVegas95

2023-07-03 03:14 UTC, Gorgy requested changes

2023-07-03 03:14 UTC, Gorgy commented on src/App.tsx
> +    <Route path="/" element={<Main active={false} modalActive={false} setActive={false} setModalActive={false}/>}/>
Не стоит в рутах передавать props, все манипуляции лучше оставить внутри компонента

2023-07-03 03:14 UTC, Gorgy commented on src/page/Main.tsx
> +        <Title title={'Авторизация'} />
Строки в props

2023-07-03 19:49 UTC, Gorgy requested changes

2023-07-03 19:49 UTC, Gorgy commented on src/app.interface.ts
> +  children: any
children есть в дженерике реакта PropsWithChildren

2023-07-04 17:07 UTC, Gorgy commented on src/content/main-text.ts
> +const mainText = 'Только для зарегистрированных пользователей';
А смысл в этом файле?

2023-07-04 17:07 UTC, Gorgy commented on src/moduls/modal/Components/Modal.tsx
> +    <div className={modalActive ? 'modal__content active' : 'modal'} onClick={e => e.stopPropagation()}>
зачем `onClick`?

2023-07-04 17:08 UTC, Gorgy commented
`.prettierrc` подключи и настрой

2023-07-04 17:08 UTC, Gorgy approved these changes

2023-07-04 17:16 UTC, NikitaVegas95 commented on src/content/main-text.ts
> +const mainText = 'Только для зарегистрированных пользователей';
Про комментарий к строкам в пропсах, подумал, что нужно вынести в отдельные переменные

2023-07-04 17:16 UTC, NikitaVegas95 commented on src/moduls/modal/Components/Modal.tsx
> +    <div className={modalActive ? 'modal__content active' : 'modal'} onClick={e => e.stopPropagation()}>
Вынести в отдельные функции и передать пропсом?

2023-07-04 19:45 UTC, merged